[book]
authors = ["Steven Deobald", "Håkan Råberg"]
language = "en"
multilingual = false
src = "src"
title = "The Endatabas Book"

# chapter-level ToC ... perhaps not necessary,
# but it's here if we want it.
[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html", "pdf"]

[output.html]

[output.html.print]
enable = true

[output.pdf]
# theme = "ayu"

[output.pdf-outline]
