[book]
authors = ["Steven Deobald", "Håkan Råberg"]
language = "en"
multilingual = false
src = "src"
title = "The Endatabas Book"

[build]
build-dir = "docs"

[output.html]
cname = "docs.endatabas.com"

[output.html.print]
enable = true

[output.linkcheck]
