[book]
authors = ["Steven Deobald", "Håkan Råberg"]
language = "en"
multilingual = false
src = "src"
title = "The Endatabas Book"

[build]
# we use a non-standard build dir so it's clearer that it isn't the destination
build-dir = "output"

[output.html]
cname = "docs.endatabas.com"
git-repository-url = "https://github.com/endatabas/endb-book"
edit-url-template = "https://github.com/endatabas/endb-book/edit/main/{path}"

[output.html.print]
enable = true

[output.linkcheck]
