[book]
authors = ["Steven Deobald", "Håkan Råberg"]
language = "en"
multilingual = false
src = "src"
title = "The Endatabas Book"

[output.html]

[output.html.print]
enable = true

[output.pdf]
theme = "ayu"

[output.pdf-outline]

